# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f25d5210d4d470f4826e1cab7867a18e4670890df951f8a2f6057ce607be6c09d0d85718416830d36295c6f4f775d3c7b4582c1ef220361ff1ddd6571981cdc

test:
  secret_key_base: 3354c9db9a58fde550ee372cc85560596cd81bb6bb43e44b41d1426223d6c650d4b065da9c92270eebd10b48bd00649587656270d663df713c02d8ce26c09066

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
